Models/CategoriesRepo.cs
namespace WebApplication1.Models;

public class CategoriesRepo
{
    private static List<Category> _categories = new List<Category>()
    {
        new Category {CategoryId = 1, Name = "Beverage", Description = "Beverage"},
        new Category {CategoryId = 2, Name = "Bakery", Description = "Bakery"},
        new Category {CategoryId = 3, Name = "Meeat", Description = "Meeat"}
    };

    public static void AddCategory(Category category)
    {
        var maxId = _categories.Max(x => x.CategoryId);
        category.CategoryId = maxId + 1;
        _categories.Add(category);
    }

    public static List<Category> GetCategories() => _categories;

    public static Category? GetCategoryById(int categoryId)
    {
        var category = _categories.FirstOrDefault(x => x.CategoryId == categoryId);
        if (category != null)
        {
            return new Category
            {
                CategoryId = category.CategoryId,
                Name = category.Name,
                Description = category.Description
            };
        }

        return null;
    }

    public static void UpdateCategory(int categoryId, Category category)
    {
        if (categoryId != category.CategoryId) return;

        var categoryToUpdate = _categories.FirstOrDefault(x => x.CategoryId == categoryId);
        if (categoryToUpdate != null)
        {
            categoryToUpdate.Name = category.Name;
            categoryToUpdate.Description = category.Description;
        }
    }

    public static void DeleteCategory(int categoryId)
    {
        var category = _categories.FirstOrDefault(x => x.CategoryId == categoryId);
        if (category != null)
        {
            _categories.Remove(category);
        }
    }
}

Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models;

public class Category
{
    public int CategoryId { get; set; }
    [Required]
    public string Name { get; set; } = string.Empty;
    public string? Description { get; set; } = string.Empty;
}

Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers;

public class CategoriesController : Controller
{
    // GET
    public IActionResult Index()
    {
        var categories = CategoriesRepo.GetCategories();
        return View(categories);
    }
    
    public IActionResult Edit(int? id)
    {
        ViewBag.Action = "Edit";
        
        var category = CategoriesRepo.GetCategoryById(id.HasValue?id.Value:0);
        
        return View(category);
    }
    
    [HttpPost]
    public IActionResult Edit(Category category)
    {
        if (ModelState.IsValid)
        {
            CategoriesRepo.UpdateCategory(category.CategoryId, category);
            return RedirectToAction(nameof(Index));
        }

        return View(category);
    }
    
    public IActionResult Add(int? id)
    {
        ViewBag.Action = "Add";
        
        return View();
    }
    
    [HttpPost]
    public IActionResult Add(Category category)
    {
        if (ModelState.IsValid)
        {
            CategoriesRepo.AddCategory(category);
            return RedirectToAction(nameof(Index));
        }

        return View(category);
    }

    public IActionResult Delete(int categoryId)
    {
        CategoriesRepo.DeleteCategory(categoryId);
        return RedirectToAction(nameof(Index));
    }
    
    
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers;

public class HomeController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
}

Views/Categories/Add.cshtml
@using WebApplication1.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model Category

@section title {
    <h3>Category</h3>
}

<partial name="_Category" model="@Model"/>

Views/Categories/Edit.cshtml
@using WebApplication1.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model Category

@section title {
    @if (Model != null)
    {
        <h3>Category: @Model.Name</h3>
    }
}

@if (Model != null)
{
    <partial name="_Category" model="@Model"/>
}

Views/Categories/Index.cshtml
@using WebApplication1.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model List<Category>

@section title {
    <h1 class="text-purple-500">Categories</h1>
}
@if (Model != null && Model.Count() > 0)
{
    <div class="relative h-auto">
        <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-white-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">Name</th>
                <th scope="col" class="px-6 py-3">Description</th>
                <th scope="col" class="px-6 py-3"></th>
                <th scope="col" class="px-6 py-3"></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var category in Model)
            {
                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                    <td class="px-6 py-4">@category.Name</td>
                    <td class="px-6 py-4">@category.Description</td>
                    <td>
                        <a asp-controller="Categories" asp-action="Edit" asp-route-id="@category.CategoryId" class="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700">
                            Edit
                        </a >
                    </td>
                    <td><a asp-controller="Categories" asp-action="Delete" asp-route-categoryId="@category.CategoryId" onclick="confirmDelete()" class="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700">Delete</a></td>
                </tr>
            }
            </tbody>
        </table>
        <br/>
        <a asp-controller="Categories" asp-action="Add" class="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700">
            Add
        </a>
    </div>
}

@section Scripts{
    <script>
        function confirmDelete(){
            return confirm("Are you sure you want to delete this category?");
        }
    </script>
}

Views/Categories/_Category.cshtml
@using WebApplication1.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model Category

@{
    string action = ViewBag.Action ?? string.Empty;
}

<form method="post" asp-controller="Categories" asp-action="@action">
    @if (action == "Edit")
    {
        <input type="hidden" asp-for="CategoryId"/>
    }
    <div class="text-red-600" asp-validation-summary="All"></div>
    <div class="max-w-lg ml-6">
        <div class="grid grid-cols-1 gap-y-4">
            <div class="flex items-center">
                <label for="Name" class="w-32 text-sm font-medium text-gray-700">Name:</label>
                <input type="text" asp-for="Name" id="Name" class="flex-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
            </div>
            <div class="flex items-center">
                <label for="Description" class="w-32 text-sm font-medium text-gray-700">Description:</label>
                <textarea asp-for="Description" id="Description" rows="3" class="flex-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"></textarea>
            </div>
        </div>
        <div class="mt-4">
            <button type="submit" class="inline-flex items-center px-4 py-2 bg-green-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-green-700 active:bg-green-700 focus:outline-none focus:border-green-700 focus:ring focus:ring-green-300 disabled:opacity-25 transition">Save</button>
        </div>
    </div>
</form>

Views/Home/Index.cshtml
@section title {
    <h1 class="text-purple-500">Homepage</h1>
}
<br/>
<p class="text-sky-400">The quick brown fox...</p>

<p>This is the home page</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link href="~/css/output.css" rel="stylesheet" asp-append-version="true">
</head>
<body>


<ul class="flex w-full border-b-2 p-4">
    <l1 class="mr-6">Website</l1>
    <li class="mr-6">
        <a class="text-gray-500 hover:text-gray-800" href="/home/Index">Home</a>
    </li>
    <li class="mr-6">
        <a class="text-gray-500 hover:text-gray-800" href="/categories/Index">Categories</a>
    </li>
</ul>

<div class="container">
    <div class="container pb-3">
        @RenderSection("title")
        <hr/>
    </div>
    <div class="container">
        @RenderBody()
    </div>
</div>
@await RenderSectionAsync("Scripts", required: false )
</body>
</html>